services:
  - type: web
    name: altar-app-backend
    env: node
    buildCommand: |
      cd backend && npm install
      cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://altar-app-backend.onrender.com
      - key: PORT
        value: 10000
      - key: MAX_FILE_SIZE
        value: 20mb 